services:
  api:
    build: .
    ports:
      - '8000:8000'
    environment:
      OLLAMA_URL: http://host.docker.internal:11434
    volumes:
      - ./chroma_db:/app/chroma_db
    extra_hosts:
      - 'host.docker.internal:host-gateway'
